
#--------------------- DB Connection ------------------
spring.datasource.url=jdbc:postgresql://${API_PG_ADDR_PROD}/api_db
spring.datasource.username=${POSTGRES_USER_PROD}
spring.datasource.password=${POSTGRES_PASSWORD_PROD}
spring.datasource.driver-class-name=org.postgresql.Driver

aghu.api.base-url=https://prod.huwc.ufc.br

aghu.api.token=${AGHU_API_TOKEN:default-token-if-empty}
