
#--------------------- DB Connection ------------------
spring.datasource.url=jdbc:postgresql://${API_PG_ADDR}/petsd_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

aghu.api.base-url=https://prod.huwc.ufc.br

aghu.api.token=${AGHU_API_TOKEN:default-token-if-empty}

# URL do realm (ISSUER)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://hggat3.huwc.ufc.br/auth/realms/hmg
