#--------------------- DB Connection ------------------
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none

# --- JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# --- Desabilitar o banner e logs extensos ---
spring.main.banner-mode=off
logging.level.org.springframework=warn

spring.main.allow-bean-definition-overriding=true

# --- Desabilitar a seguranÃ§a durante os testes ---
spring.autoconfigure.exclude=\
# org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Valor para os testes de integração do pipeline
aghu.api.token=${AGHU_TOKEN:mock-token}
aghu.api.base-url=${AGHU_API_BASE_URL:http://localhost:8080}